In [67]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [68]:
dataset = pd.read_csv('Churn_Modelling.csv')


In [69]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [70]:
x = dataset.iloc[:, 3:13]
y = dataset.iloc[:, 13]

In [71]:
x.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [72]:
x.Geography.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [73]:
# We'll Convert Geography into Categorical Sense
geography = pd.get_dummies(x['Geography'],dtype=int, drop_first=True) # Frop First Means it'll Delete First Column(if All Remaining is 0 thel obiviously it's Belonging to first (dropped) column)
gender = pd.get_dummies(x['Gender'],dtype=int, drop_first=True)

In [74]:
gender

Male
0        0
1        0
2        0
3        0
4        0
...    ...
9995     1
9996     1
9997     0
9998     1
9999     0

[10000 rows x 1 columns]

In [75]:
# Drop Existing Geography and Gender Feature
x = x.drop(['Geography','Gender'],axis=1)

In [76]:
x.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  
0               1        101348.88  
1               1        112542.58  
2               0        113931.57  
3               0         93826.63  
4               1         79084.10

In [77]:
# Merging New Numerical Column
x = pd.concat([x,geography,gender],axis=1)

In [78]:
# Splitting Data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0,test_size=0.2)

In [79]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
ssc = StandardScaler()
x_train = ssc.fit_transform(x_train)
x_test = ssc.transform(x_test)

In [80]:
x_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [81]:
x_test

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]])

In [82]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import LeakyReLU,PReLU,ELU,ReLU
from tensorflow.keras.optimizers import Adam

In [83]:
classifier = Sequential()

In [84]:
classifier.add(Dense(units=11,activation='relu'))

In [85]:
classifier.add(Dense(units=7,activation='relu'))

In [86]:
classifier.add(Dense(units=6,activation='relu'))

In [87]:
classifier.add(Dense(1, activation='sigmoid'))

In [88]:
opt = Adam(learning_rate=0.01)

In [89]:
import tensorflow as tf
early_stopping=tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0.0001,
    patience=20,
    verbose=1,
    mode="auto",
    baseline=None,
    restore_best_weights=False
)

In [90]:
classifier.compile(optimizer=opt, loss = 'binary_crossentropy',metrics=['accuracy'])

In [91]:
# tf.compat.v1.enable_eager_execution()

In [92]:
model = classifier.fit(x_train,y_train,epochs=100,validation_split=0.33,batch_size = 10, callbacks=None)

Epoch 1/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 21s 14ms/step - accuracy: 0.8110 - loss: 0.4625 - val_accuracy: 0.8133 - val_loss: 0.4136
Epoch 2/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 12s 14ms/step - accuracy: 0.8478 - loss: 0.3743 - val_accuracy: 0.8527 - val_loss: 0.3622
Epoch 3/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8466 - loss: 0.3665 - val_accuracy: 0.8497 - val_loss: 0.3703
Epoch 4/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.8504 - loss: 0.3532 - val_accuracy: 0.8516 - val_loss: 0.3571
Epoch 5/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.8644 - loss: 0.3259 - val_accuracy: 0.8550 - val_loss: 0.3544
Epoch 6/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.8639 - loss: 0.3357 - val_accuracy: 0.8584 - val_loss: 0.3509
Epoch 7/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8667 - loss: 0.3295 - val_accuracy: 0.8501 - val_loss: 0.3613
Epoch 8/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8571 - loss: 0.3362 - val_

In [61]:
x_train.shape

(8000, 11)

In [97]:
y_pred = classifier.predict(x_test)
y_pred

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


array([[0.18340398],
       [0.2969633 ],
       [0.11646344],
       ...,
       [0.92078304],
       [0.15787306],
       [0.12243997]], dtype=float32)

In [98]:
y_pred= (y_pred >= 5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [101]:
from sklearn.metrics import confusion_matrix,accuracy_score

score = confusion_matrix(y_test,y_pred)
score

array([[1595,    0],
       [ 405,    0]], dtype=int64)

In [102]:
accuracy_score(y_test,y_pred)

0.7975

In [114]:
y_pred.size

2000